/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Order
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object OrdersApi {

  /**
   * Adds an order to the system
   * 
   * Expected answers:
   *   code 201 : Any (order created)
   *   code 400 :  (invalid input, object invalid)
   * 
   * @param order order object to add (without orderId )
   */
  def postOrder(order: Option[Order] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.POST, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/placeOrder", "application/json")
      .withBody(order)
      .withSuccessResponse[Any](201)
      .withErrorResponse[Unit](400)
      

}

