/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Product
import io.swagger.client.model.Slug
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ProductsApi {

  /**
   * By passing in the appropriate options, you can retrieve available menu slugs in the system 
   * 
   * Expected answers:
   *   code 200 : Seq[Slug] (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param lang the language
   * @param country the country
   * @param slug the slug
   * @param userId the logged in user (if any)
   */
  def getFilters(lang: String, country: String, slug: Option[String] = None, userId: Option[String] = None): ApiRequest[Seq[Slug]] =
    ApiRequest[Seq[Slug]](ApiMethods.GET, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/getfilters", "application/json")
      .withQueryParam("lang", lang)
      .withQueryParam("country", country)
      .withQueryParam("slug", slug)
      .withQueryParam("userId", userId)
      .withSuccessResponse[Seq[Slug]](200)
      .withErrorResponse[Unit](400)
        /**
   * By passing in the appropriate options, you can retrieve a specific product in the system 
   * 
   * Expected answers:
   *   code 200 : Product (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param lang the language
   * @param country the country
   * @param id the id of the product
   * @param userId the logged in user (if any)
   */
  def getProduct(lang: String, country: String, id: String, userId: Option[String] = None): ApiRequest[Product] =
    ApiRequest[Product](ApiMethods.GET, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/getproduct", "application/json")
      .withQueryParam("lang", lang)
      .withQueryParam("country", country)
      .withQueryParam("id", id)
      .withQueryParam("userId", userId)
      .withSuccessResponse[Product](200)
      .withErrorResponse[Unit](400)
        /**
   * By passing in the appropriate options, you can retrieve a list of products for a specific slug in the system 
   * 
   * Expected answers:
   *   code 200 : Seq[String] (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param lang the language
   * @param country the country
   * @param slug the slug to query
   * @param userId the logged in user (if any)
   */
  def getProducts(lang: String, country: String, slug: String, userId: Option[String] = None): ApiRequest[Seq[String]] =
    ApiRequest[Seq[String]](ApiMethods.GET, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/getproducts", "application/json")
      .withQueryParam("lang", lang)
      .withQueryParam("country", country)
      .withQueryParam("slug", slug)
      .withQueryParam("userId", userId)
      .withSuccessResponse[Seq[String]](200)
      .withErrorResponse[Unit](400)
      

}

