/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UsersApi {

  /**
   * By passing in the appropriate options, you can login in the system 
   * 
   * Expected answers:
   *   code 200 : User (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param lang the language
   * @param country the country
   * @param email the user&#39;s email
   * @param password the user&#39;s password
   */
  def login(lang: String, country: String, email: String, password: String): ApiRequest[User] =
    ApiRequest[User](ApiMethods.GET, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/login", "application/json")
      .withQueryParam("lang", lang)
      .withQueryParam("country", country)
      .withQueryParam("email", email)
      .withQueryParam("password", password)
      .withSuccessResponse[User](200)
      .withErrorResponse[Unit](400)
        /**
   * Adds a user to the system
   * 
   * Expected answers:
   *   code 201 : Any (user created)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing user already exists)
   * 
   * @param user user object to add (without userid )
   */
  def register(user: Option[User] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.POST, "https://virtserver.swaggerhub.com/akyriak/mobileShop/1.0.0", "/register", "application/json")
      .withBody(user)
      .withSuccessResponse[Any](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
      

}

