/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Address (
  addressId: Option[UUID],
  title: Option[String],
  description: Option[String],
  street: Option[String],
  city: Option[String],
  region: Option[String],
  country: Option[String],
  tel: Option[String],
  zip: Option[String],
  pobox: Option[String]
) extends ApiModel


