/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Product (
  id: Option[UUID],
  slug: Option[String],
  title: Option[String],
  description: Option[String],
  startingPrice: Option[Double],
  price: Option[Double],
  composition: Option[String],
  photos: Option[Seq[Photo]],
  video: Option[Video],
  sizes: Option[Seq[String]],
  colors: Option[Seq[Color]]
) extends ApiModel


